ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/ydlidar
    frame_id: laser_link
    ignore_array: ""
    baudrate: 115200 
    lidar_type: 1
    device_type: 0
    sample_rate: 3
    abnormal_check_count: 4
    resolution_fixed: true
    reversion: false 
    inverted: true 
    auto_reconnect: true
    isSingleChannel: true
    intensity: false
    support_motor_dtr: false
    angle_max: 180.0
    angle_min: -180.0
    range_max: 12.0
    range_min: 0.01
    frequency: 8.0
    invalid_range_is_inf: false
